feat: Timecode & scheduler
CasparCG/server pull request #1140
Opened 2018-12-19 11:29 UTC by Julusian

#871 #872 #1004

This adds support for timecode input and output via decklinks, and for being able to schedule commands to be executed at various timecodes. It also adds a batch command syntax to amcp.

To be able to use a decklink as the source, it must exist on the stage. To allow this from startup, the xml config can now have producers defined.

Further docs: https://docs.google.com/document/d/1xkksxIdNHMO95RFF8wJ3vYRbXCHwKnjkMwVqwAyjv3A/edit?usp=sharing

2018-12-19 18:04 UTC, ronag commented
Can you put the AMCP updates into a separate PR?

2018-12-19 18:11 UTC, ronag commented on src/modules/decklink/producer/decklink_producer.cpp
> +                new_timecode = new_timecode - (format_desc_.field_count > 1 ? 3 : 1);
This is not going to be entirely accurate...

2018-12-19 18:11 UTC, ronag commented on src/modules/decklink/producer/decklink_producer.cpp
> +                new_timecode = new_timecode - (format_desc_.field_count > 1 ? 3 : 1);
Hm, no that's a bad idea, but I still think you can measure the filter latency using pts

2018-12-19 18:12 UTC, ronag commented on src/modules/decklink/producer/decklink_producer.cpp
> +                new_timecode = new_timecode - (format_desc_.field_count > 1 ? 3 : 1);
hmm... maybe this is good enough in practice

2018-12-19 18:12 UTC, ronag commented on src/modules/decklink/producer/decklink_producer.cpp
> +                new_timecode = new_timecode - (format_desc_.field_count > 1 ? 3 : 1);
leave it

2019-04-05 07:47 UTC, ronag commented
@Julusian I have it on my list to go through this... can you please resolve the conflicts?

2019-10-22 11:12 UTC, didikunz commented
Hi, is there a build with that included? It looks to me, that it's still not merged into the main branch, right?

2019-10-22 11:16 UTC, ronag commented
@didikunz: Not merged. There are lot's of conflicts.

2019-10-22 11:43 UTC, didikunz commented
I would encourage @Julusian or who ever is responsible to resolve this, as this is a power full feature. Is it in the NHK builds?

2019-10-22 11:43 UTC, MauriceVeraart commented
Yes

2020-01-15 08:23 UTC, swordh commented
Hi Guys,
Love the work, keep it up :)  waiting for this feature to be merged, only reason that I use the NRK version and Windows. 
Are there any plans on getting this merged soon?

2022-08-08 03:04 UTC, poldon commented
Is there any plan to merge this still?  This is a very good feature, and one I think a lot of people will benefit from.

2022-10-07 08:35 UTC, GeorgNation requested changes
I think it should be in release. The only thing missing is the ability to switch the time zone, timecode with a drop frame, specifying milliseconds and the ability to hold an event. This would make the tool ideal.

2023-12-24 00:09 UTC, Julusian commented
I think it is time to close this PR, discussion can continue here or in the issue #871 

The client who originally funded this work no longer has an interest in it, and some more work is needed to flesh out timecode support to make it more usable.
I am not entirely sure on the resulting quality of this change as it was never used in production (other than with the default config of following the system clock). For this to be actually useful to anyone, I expect that support will need to be added to the ffmpeg_producer, and possibly more producers and consumers.

I've had a quick attempt at rebasing this onto current builds, as there were pretty major merge conflicts due to various portions of this having been picked and merged already. If anyone wants to continue working on this you can start with https://github.com/CasparCG/server/commit/056c9469da08b5c958ccf5fc12713e62a94490fa

I have no interest in the scheduler portion of this PR, we found it to be hard to work with and to understand the state of the system when cancelling commands or amending the scheduled commands.

2023-12-24 00:09 UTC, closed without merging