feat: port 2.1 image scroll producer
CasparCG/server pull request #1372
Opened 2021-02-21 11:19 UTC by ronag

2021-03-06 17:00 UTC, ronag commented
@5opr4ni this is ready for you to be verified

2021-03-07 05:56 UTC, 5opr4ni commented
> @5opr4ni this is ready for you to be verified

I’ll have a look. Was in transmission when I saw it, and almost missed putting on some graphics. 🤣 (Mello)

2021-03-09 13:23 UTC, dotarmin commented
@ronag This is not building unfortunately on the build server. It complains about unresolved external symbols and the build fails with two errors of the same type (see below).

`error LNK2019: unresolved external symbol` 

Other branches works as expected.

2021-03-09 14:19 UTC, ronag commented
Probably missing a reference to the cpp file in some make file.

2021-03-09 19:19 UTC, dotarmin commented
> Probably missing a reference to the cpp file in some make file.

Roger that. Let me know when you have looked at it so I can run the build.

2021-03-10 13:52 UTC, 5opr4ni commented
All expected commands works as expected regarding to function but not time.
Duration and end_time are probably based on another time. (A DURATION of 20 took 40 seconds.)
These commands where tested:
PLAY 1-10 mellocred speed 8

PLAY 1-10 mellocred speed 4 BLUR 4

PLAY 1-10 mellocred speed 8 BLUR 10

PLAY 1-10 hscrolltest speed 8 BLUR 10

PLAY 1-10 mellocred DURATION 20 BLUR 4

PLAY 1-10 mellocred END_TIME "2021-03-10 14:45:17"

2021-03-11 12:45 UTC, 5opr4ni requested changes
All expected commands works as expected regarding to function but not time.
Duration and end_time are probably based on another time. (A DURATION of 20 took 40 seconds.)

2021-03-11 16:28 UTC, ronag commented on src/modules/image/producer/image_scroll_producer.cpp
> +        return get_total_num_pixels() / (duration_seconds * format_desc_.fps * static_cast<double>(format_desc_.field_count));
```suggestion
        return get_total_num_pixels() / (duration_seconds * format_desc_.fps);
```

2021-03-15 15:20 UTC, 5opr4ni approved these changes

2021-03-15 15:22 UTC, 5opr4ni commented
Tested hard during rehearsals and broadcast of Melodifestivalen. Worked flawlessly! 🥳

2021-03-15 19:11 UTC, merged